package johan.raderas;

import android.content.Intent;
import android.support.v7.app.ActionBarActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListAdapter;
import android.widget.ListView;
import com.firebase.client.DataSnapshot;
import com.firebase.client.Firebase;
import com.firebase.client.FirebaseError;
import com.firebase.client.ValueEventListener;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Firebase.setAndroidContext(this);

        String FIREBASE_URL = "https://luminous-heat-420.firebaseio.com/";
        Firebase firebase = new Firebase(FIREBASE_URL);

        CreateNewGroup(firebase);
        ReadData(firebase);
        //UpdateInfo(firebase);


    }

    public void CreateNewGroup(Firebase firebaseRef) {
        String name = "alans grupp";
        String id = firebaseRef.push().getKey();

        if ((!name.isEmpty() && !id.isEmpty())) {
            Firebase groupID = firebaseRef.child("id");
            groupID.setValue(id);

            Firebase groupName = firebaseRef.child("name");
            groupName.setValue(name);
        }
    }

    public void AddDataToListView(String groupName) {

        ListView view = (ListView) findViewById(R.id.lstView);
        ArrayList<String> arrList = new ArrayList<String>();

        arrList.add(groupName);

        ListAdapter arrAdapter = new ArrayAdapter(this, android.R.layout.simple_list_item_1, arrList);

        view.setAdapter(arrAdapter);

        view.setOnItemClickListener(mOnItemClickListener);

    }

    public void UpdateInfo(Firebase firebase) {
        Firebase ref = firebase.child("gracehop");
        Map<String, Object> nickname = new HashMap<String, Object>();
        nickname.put("nickname", "Amazing grace");
        ref.updateChildren(nickname);
    }

    public  void CreateNewPost(Firebase firebase) {
        // Generate a reference to a new location and add some data using push()
        Firebase postRef = firebase.child("posts");
        Firebase newPostRef = postRef.push();

        // Add some data to the new location
        Map<String, String> post1 = new HashMap<String, String>();
        post1.put("author", "gracehop");
        post1.put("title", "Announcing COBOL, a New Programming Language");
        newPostRef.setValue(post1);

        // Get the unique ID generated by push()
        String postId = newPostRef.getKey();
        System.out.println(postId);
    }

    public void ReadData(final Firebase firebase) {
        firebase.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot snapshot) {
                Map<String, Object> newPost = (Map<String, Object>) snapshot.getValue();
                String groupName = newPost.get("name").toString();

                if (!groupName.isEmpty()) {
                    AddDataToListView(groupName);
                    Log.d("Added new group to group list: ", groupName);
                } else {
                    Log.d("No group name could be found:", groupName);
                }
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                System.out.println("The read failed: " + firebaseError.getMessage());
            }
        });

    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    public AdapterView.OnItemClickListener mOnItemClickListener = new AdapterView.OnItemClickListener() {
        @Override
        public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
            Intent intent = new Intent(view.getContext(), ChatActivity.class);
            startActivity(intent);
        }
    };
}
